name: produits_derives_lidar
channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.9.*
  - pip
  - pytest
  - cgal==5.4
  - gdal
  - laspy
  - numpy
  - scipy
  - rasterio
  - pyproj
  - pdal>=2.4.3
  - python-pdal>=3.2.1
  - pip:
      - startinpy==0.8.0
      - -e ./ign_las_stitching

