name: produits_derives_lidar
channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.9.*
  - pip
  - pytest
  - cgal
  - gdal
  - laspy
  - geojson
  - shapely
  - pandas
  - numpy
  - scikit-learn
  - geopandas
  - scipy
  - rasterio
  - pdal>=2.4.3
  - python-pdal>=3.2.1
  - pip:
      - postgis-toolkit
      - startinpy

