name: las_digital_models
channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.10.*
  - pip
  - pytest
  - gdal
  - laspy
  - numpy
  - fiona
  - pyproj
  - pdal>=2.9.0
  - python-pdal>=3.4.0
  - geopandas
  - parallel
    # --------- hydra configs --------- #
  - hydra-core==1.2.*
  - hydra-colorlog==1.2.*
    # --------- build and deploy lib -- #
  - build
  - twine
    # --------- linting --------------- #
  - black
  - flake8
  - isort
  - pre-commit
  - pip:
      - ign-pdal-tools
      - rasterstats
      - rasterio # moved here since pdal>=2.9.0 force modern libs to be used and make dependancy graph non resolved