name: las_digital_models
channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.12.*
  - pip
  - pytest
  - gdal
  - laspy
  - numpy
  - fiona
  - pyproj
  - pdal>=2.9.0
  - python-pdal>=3.4.0
  - geopandas
  - parallel
  - rasterstats
  - rasterio
  # --------- hydra configs --------- #
  - hydra-core
  - hydra-colorlog
  # --------- build and deploy lib -- #
  - twine
    # --------- linting --------------- #
  - black
  - flake8
  - isort
  - pre-commit
  - pip:
    - build
    - ign-pdal-tools
