name: las_digital_models
channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.10.*
  - pip
  - pytest
  - cgal
  - gdal
  - laspy
  - numpy
  - scipy
  - fiona
  - rasterio
  - pyproj
  - pdal>=2.6
  - python-pdal>=3.2.1
  - geopandas
  - parallel
    # --------- hydra configs --------- #
  - hydra-core==1.2.*
  - hydra-colorlog==1.2.*
    # --------- build and deploy lib -- #
  - build
  - twine
    # --------- linting --------------- #
  - black
  - flake8
  - isort
  - pre-commit
  - pip:
      - ign-pdal-tools
      - rasterstats

