# Folder containing the input tiles (filtered and potentially with buffer added).
# (set to `--output_dir` if not provided).
input_dir: /path/to/origin/las/folder
input_filename: filename.las

input_raster_dir: path/to/origin/raster/folder
input_raster_filename: filename.tiff

input_geometry_dir: /path/to/origin/geometry/folder
input_geometry_filename: filename.shp

# Shapefile used to burn no-data value (inside its polygons)
no_data_mask_shapefile: null  # /path/to/mask.shp

# Force input/output files extension to .las or .laz. If None or not set, use original extension
# Used for output for filter
# Used for input + output in buffer
# Use for input in interpolation
forced_intermediate_ext: null  # can be "las", "laz" or null. (intermediate results extension)

# Spatial reference to use to override the one from input las.
spatial_reference: EPSG:2154

output_dir: /path/to/output/folder  # Directory folder for saving the outputs





