input_dir: ./test/data/
input_filename: test_data_77055_627760_LA93_IGN69.laz
no_data_mask_shapefile: null

forced_intermediate_ext: null

spatial_reference: EPSG:2154

output_dir: ./test/tmp/hydra_ip

# To be used only when using dhm_one_tile directly (standalone mode) to run
# DHM from any input DTM and DSM
# DSM and DTM are associated to the tile by their names, which should be like:
#  f"{input filename without extension}_{pixel size with unit}"
input_dsm_dir: ./test/data/DSM
input_dtm_dir: ./test/data/DTM