# Folder containing the input raster tiles and geometry.
# (set to `--output_dir` if not provided).
input_raster_dir: path/to/origin/raster/folder

input_geometry_dir: /path/to/origin/geometry/folder
input_geometry_filename: filename.shp

input_vrt_path: /path/to/origin/geometry/folder/filename.vrt

# Spatial reference to use to override the one from input raster.
spatial_reference: EPSG:2154

output_dir: /path/to/output/folder  # Directory folder for saving the outputs
output_geometry_filename: filename.GeoJSON