output_subfolder: "DHM"

# To be used only when using dhm_one_tile directly (standalone mode) to run
# dhm from any input dtm and dsm
# DSM and DTM are associated to the tile by their names, which should be like:
#  f"{input filename without_extension}_{pixel_size with unit}"
input_dtm_dir: ./test/data/DTM
input_dsm_dir: ./test/data/DSM

