# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# specify here default training configuration
defaults:
  - _self_  # for hydra legacy reasons

  - interpolation: startin-laplace.yaml
  - io: default.yaml
  - tile_geometry: default.yaml  # describes input features and classes

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: disabled


# hydra:
#   # job.chdir: False
#   hydra_logging: colorlog
#   job_logging: colorlog