# @package _global_

# Special config used for tests (test_run_script.py)
work_dir: ${hydra:runtime.cwd}

defaults:
  - _self_  # for hydra legacy reasons

  - buffer: test.yaml
  - filter: default_test.yaml
  - io: test.yaml
  - tile_geometry: test.yaml  # describes input features and classes
  - dhm: test.yaml

  # disable hydra logging
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
