name: produits_derives_lidar
channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.9.*
  - pip
  # --------- geo --------- #
  #- conda-forge:pdal==2.3.*
  #- conda-forge:python-pdal==3.0.*
  - gdal
  - laspy
  - geojson
  - shapely
  - pandas
  - numpy
  - scikit-learn
  - geopandas
  - scipy
  - rasterio
  - python-pdal
  - pip:
      - postgis-toolkit
      - startinpy

